development:
  adapter: postgresql
  encoding: unicode
  database: sweet_articles_rails_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sweet_articles_rails_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sweet_articles_rails_production
  pool: 5
  username:
  password:
